# This is a basic workflow to help you get started with Actions

name: Pull Request | Build and Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Test"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Test using node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
      - run: npm ci
      - run: npm test
      - run: tsc
      - run: npx eslint .

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v11.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGEBUMP_TOKEN }}
        with:
          minor-wording: 'bumpversion,minor,update'
          major-wording: 'MAJOR'
          patch-wording: 'patch,fixes,add,Adds,new'

